openapi: 3.0.2
info:
  version: 1.0.0
  title: Example.com
  termsOfService: "https://example.com/terms/"
  contact:
    email: contact@example.com
    url: "http://example.com/contact"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-logo:
    url: "https://apis.guru/openapi-template/logo.png"
  description: >
    # Your description here
externalDocs:
  description: Find out how to create a GitHub repo for your OpenAPI definition.
  url: "https://github.com/Rebilly/generator-openapi-repo"
tags:
  - name: Echo
    description: Example echo operations
  - name: User
    description: Operations about user
servers:
  - url: "http://example.com/api/v1"
  - url: "https://example.com/api/v1"
paths:
  # paths here
components:
  securitySchemes:
    # security schemes here
security:
  - SecretAPIKey: []
  - JWT: []
